### ISSUE TITLE
gui_LoadBackground set to "scale" corrupts image

### ISSUE THREAD

**Issue by DavidSoMighty** [OrchardSoftware/4D-Win32API#5]
I'm using your plugin to load a background image to my 4D app, and images look beautiful if I set the parameter to "BM_TILE", but with "BM_SCALE" corrupts the image.  Is there any way around this?  Perhaps another image type?  Thanks.

**Comment by dwaddell** [comment]
Hello David,

After an initial test on my workstation it seems to be working correctly so we'll need a little more information to reproduce the problem.  Once we have it reproduced over here we'll get someone looking into a solution.

Can you provide us with a little more information on the issue to get it reproduced? 

1. - What version of our plugin are you using?
2. - What type of image are you using? .BMP? 
3. - What operating system are you using?

Thanks,
Drew

**Comment by DavidSoMighty** [comment]
Hello Drew,
Thank you very much for the swift response.  
1.  I'm using the win32API v6.1.
2.  I'm using a .BMP image file.
3. I've got Windows 7 sr1

I've attached the behavior I'm seeing below. This first image is set to "scaled" and you can see the strange rendering, and pixelation. 

![backgroundscale](https://cloud.githubusercontent.com/assets/8987542/6232018/536db776-b67e-11e4-8f54-47360c1366a5.jpg)

Here it is set to tile, works beautifully.
![backgroundtile](https://cloud.githubusercontent.com/assets/8987542/6232017/536da484-b67e-11e4-8405-94d44798eb03.jpg)

**Comment by DavidSoMighty** [comment]
Hey Drew,
Were you able to see the same behavior?  Let me know if you need any more information.  Thanks again.

**Comment by dwaddell** [comment]
Hello David, 

Yes, we are able to reproduce this behavior.  As far as I can remember the method has always behaved this way.  Unfortunately since we don't take full advantage of this method in our products and since Win32API is open sourced, it's a low priority issue for us and we are unlikely to apply resources to it for several months at least.  You are free to investigate a fix yourself and to share with the community if you find a solution.

**Comment by DavidSoMighty** [comment]
Fully understandable, thanks anyways.
